[build-system]
requires = ["setuptools", "wheel"]

[tool.setuptools]
zip-safe = false

[project]
name = "dragon-albion-bot"
version = "1.0.0"
requires-python = ">=3.11,<3.13"
dependencies = [
    "discord.py==2.3.2",
    "python-dotenv==1.0.0",
    "aiosqlite==0.19.0",
    "PyNaCl==1.5.0"
]
